# nixpacks.toml (repo root)

[phases.setup]
nixPkgs = ["nodejs_18", "pnpm", "openssl"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "npx turbo run build",
  "pnpm --filter ./apps/api... run build"
]

[start]
cmd = "pnpm --filter ./apps/api... run start"
